/** Harbor Blueprint style: a decisive final review sheet that makes the handoff to a human feel secure and legible. */
import { ArrowLeft, CheckCircle2, Mail, MapPin, Send, ShieldCheck } from "lucide-react";
import { Link, useLocation } from "wouter";
import { FormEvent, useState } from "react";
import SiteHeader from "@/components/SiteHeader";
import SiteFooter from "@/components/SiteFooter";
import { formatMoney } from "@/lib/catalog";
import { useRental } from "@/contexts/RentalContext";

export default function BookingConfirmation() {
  const { quoteLines, zip, customer, setCustomer, rentalTotal, depositTotal, delivery, grandTotal, clearQuote } = useRental();
  const [, navigate] = useLocation();
  const [submitted, setSubmitted] = useState(false);
  if (!quoteLines.length && !submitted) { navigate("/quote"); return null; }
  const submit = (event: FormEvent) => { event.preventDefault(); setSubmitted(true); };
  if (submitted) return <div className="app-shell"><SiteHeader /><main className="request-sent"><div className="request-sent__arch"><div className="tent-arch tent-arch--large" aria-hidden="true" /><div className="request-sent__mark"><CheckCircle2 size={34} /></div></div><div className="route-milestone route-milestone--center"><span>04</span><i /><p>Request in motion</p></div><p className="eyebrow eyebrow--gold">REQUEST RECEIVED · REF #MEC-2608</p><h1>We have the shape<br /><em>of your event.</em></h1><p>Thanks, {customer.name || "there"}. Your item list and delivery note are ready for Marigold’s event line. A real team member would follow up with final availability and next steps.</p><div className="request-sent__details"><span><Mail size={16} /> A recap is headed to {customer.email || "your inbox"}</span><span><ShieldCheck size={16} /> No payment was collected in this demo</span></div><button className="button button--navy" onClick={() => { clearQuote(); navigate("/browse"); }}>Plan another event</button></main><SiteFooter /></div>;
  return <div className="app-shell confirmation-page"><SiteHeader />
    <main><div className="confirmation-heading"><Link href="/quote"><ArrowLeft size={16} /> Back to quote</Link><p className="eyebrow eyebrow--gold">FINAL STEP · REVIEW + REQUEST</p><h1>Make sure the plan<br /><em>feels right.</em></h1><div className="route-milestone route-milestone--ink"><span>04</span><i /><p>Send the request</p></div><p>Nothing is charged yet. This is a clear request with the items, dates, estimated delivery, and refundable deposits already in view.</p></div>
      <div className="confirmation-layout"><form className="booking-form" onSubmit={submit}><section><p className="form-step">01 · Your event contact</p><div className="form-grid"><label>Name<input required value={customer.name} onChange={(event) => setCustomer({ ...customer, name: event.target.value })} placeholder="Your name" /></label><label>Email<input type="email" required value={customer.email} onChange={(event) => setCustomer({ ...customer, email: event.target.value })} placeholder="you@example.com" /></label><label>Phone<input required value={customer.phone} onChange={(event) => setCustomer({ ...customer, phone: event.target.value })} placeholder="(555) 000-0000" /></label><label>Delivery ZIP<input required maxLength={5} value={zip} readOnly aria-readonly="true" placeholder="Set in quote" /></label></div></section><section><p className="form-step">02 · Notes for the event line</p><label className="notes-field">Tell us about access, setup timing, or anything useful.<textarea value={customer.notes} onChange={(event) => setCustomer({ ...customer, notes: event.target.value })} placeholder="For example: side gate entry after 10 AM, or a patio with one stair." rows={4} /></label></section><button className="button button--gold button--full" type="submit"><Send size={17} /> Send booking request</button><p className="form-legal">By sending, you are asking Marigold to review this request. Availability is confirmed by the event line, and no payment is collected here.</p></form>
        <aside className="review-sheet"><p className="eyebrow eyebrow--gold">03 · YOUR RECAP</p><div className="review-items">{quoteLines.map((line) => <div key={line.lineId}><img src={line.item.image} alt="" /><span><b>{line.quantity} × {line.item.name}</b><small>{line.eventDate?.toLocaleDateString("en-US", { month: "short", day: "numeric", year: "numeric" })}</small></span><b>{formatMoney(line.item.price * line.quantity)}</b></div>)}</div><div className="review-delivery"><MapPin size={16} /><span><b>Delivery estimate</b><small>{zip ? `${delivery.label} · ${zip}` : "Add your ZIP in the quote"}</small></span><b>{delivery.valid ? formatMoney(delivery.fee) : "—"}</b></div><div className="review-totals"><span>Rental <b>{formatMoney(rentalTotal)}</b></span><span>Delivery <b>{delivery.valid ? formatMoney(delivery.fee) : "—"}</b></span><span>Refundable deposits <b>{formatMoney(depositTotal)}</b></span></div><div className="review-grand"><span>Request total</span><b>{formatMoney(grandTotal)}</b><small>{formatMoney(depositTotal)} returns after a good return</small></div></aside></div>
    </main><SiteFooter />
  </div>;
}
