/** Harbor Blueprint style: a transparent quote workstation with numbers held in a calm, persistent sidebar. */
import { ArrowRight, CalendarDays, Check, ChevronRight, ClipboardList, MapPin, Minus, Plus, Trash2 } from "lucide-react";
import { Link, useLocation } from "wouter";
import SiteHeader from "@/components/SiteHeader";
import SiteFooter from "@/components/SiteFooter";
import { formatMoney } from "@/lib/catalog";
import { useRental } from "@/contexts/RentalContext";

export default function QuoteBuilder() {
  const { quoteLines, zip, setZip, changeQuantity, removeLine, rentalTotal, depositTotal, delivery, grandTotal, itemCount } = useRental();
  const [, navigate] = useLocation();
  if (!quoteLines.length) return <div className="app-shell"><SiteHeader /><main className="empty-quote"><div><p className="eyebrow eyebrow--gold">YOUR LIVE QUOTE</p><h1>Nothing in the plan<br /><em>just yet.</em></h1><p>Choose an item, check its date, and it will appear here with the rental, delivery, and refundable deposit all in one place.</p><Link href="/browse" className="button button--gold">Browse available pieces <ArrowRight size={18} /></Link></div><div className="empty-quote__art"><div className="tent-arch tent-arch--large" aria-hidden="true" /><ClipboardList size={72} /><span>02</span><p>Bring the first good piece into a working plan.</p></div></main><SiteFooter /></div>;
  return <div className="app-shell quote-page"><SiteHeader />
    <main><div className="quote-heading"><div><p className="eyebrow eyebrow--gold">YOUR WORKING QUOTE</p><h1>Every useful<br /><em>detail in view.</em></h1></div><div className="quote-heading__note"><div className="route-milestone route-milestone--ink"><span>03</span><i /><p>Build the plan</p></div><p>{itemCount} item{itemCount === 1 ? "" : "s"} selected. Adjust quantities, confirm dates, then set the delivery point before you send a request.</p></div></div>
      <div className="quote-layout"><section className="quote-lines"><div className="quote-section-heading"><p>Selected pieces</p><Link href="/browse">Add another item <ChevronRight size={16} /></Link></div>{quoteLines.map((line) => <article className="quote-line" key={line.lineId}><img src={line.item.image} alt="" /><div className="quote-line__main"><p className="eyebrow">{line.item.category}</p><h2>{line.item.name}</h2><p className="quote-line__date"><CalendarDays size={15} /> {line.eventDate ? line.eventDate.toLocaleDateString("en-US", { weekday: "short", month: "short", day: "numeric", year: "numeric" }) : "Date to be confirmed"}</p><button onClick={() => removeLine(line.lineId)} className="remove-button"><Trash2 size={14} /> Remove</button></div><div className="quote-line__controls"><div className="quantity-control quantity-control--small"><span>Quantity</span><div><button onClick={() => changeQuantity(line.lineId, line.quantity - 1)} aria-label={`Decrease ${line.item.name} quantity`}><Minus size={14} /></button><b>{line.quantity}</b><button onClick={() => changeQuantity(line.lineId, line.quantity + 1)} aria-label={`Increase ${line.item.name} quantity`}><Plus size={14} /></button></div></div><p><b>{formatMoney(line.item.price * line.quantity)}</b> rental</p><p><b>{formatMoney(line.item.deposit * line.quantity)}</b> deposit</p></div></article>)}</section>
        <aside className="quote-summary"><div className="quote-summary__head"><p className="eyebrow eyebrow--gold">QUOTE TOTAL</p><h2>Plan, not a surprise.</h2></div><label className="zip-field"><span><MapPin size={15} /> Delivery ZIP code</span><input inputMode="numeric" maxLength={5} value={zip} onChange={(event) => setZip(event.target.value.replace(/\D/g, ""))} placeholder="e.g. 48362" /></label><p className={delivery.valid ? "delivery-feedback delivery-feedback--valid" : "delivery-feedback"}>{delivery.valid ? <Check size={14} /> : null}{delivery.label}{delivery.valid && <b>{formatMoney(delivery.fee)}</b>}</p><div className="summary-lines"><span>Rental subtotal <b>{formatMoney(rentalTotal)}</b></span><span>Estimated delivery <b>{delivery.valid ? formatMoney(delivery.fee) : "—"}</b></span><span>Refundable deposits <b>{formatMoney(depositTotal)}</b></span></div><div className="summary-total"><span>Total to reserve</span><b>{formatMoney(grandTotal)}</b><small>Includes {formatMoney(depositTotal)} in refundable deposits</small></div><button onClick={() => navigate("/confirmation")} className="button button--gold button--full">Review booking request <ArrowRight size={17} /></button><p className="quote-summary__note">Your request is not final until Marigold confirms it. The deposit is returned within 3 business days after a good return.</p></aside></div>
    </main><SiteFooter />
  </div>;
}
